### PR TITLE
fix: Restorer should restore focus when element is removed in Safari & Firefox

### LINKED ISSUE #305: Restorer relies on focusout event firing when element is removed
Safari does not fire `focusout` or any other events when a node is removed, which means focus isn't restored when the restorer source is unmounted, even though focus returns to the body.

This can be reproduced in the Restorer stories in Safari, and also in FUI in components with popups (e.g. Popover, Dialog, Menu, etc.).

### PR DESCRIPTION
**Pull request by smhigley**
Fixes #305

Not sure if this is the best approach, but it does fix the root issue. Some of the constraints are:

- `document.activeElement` has already been set to `body` by the time the MutationObserver removedNodes mutation is detected
- Non-Chromium browsers fire literally no events when the focused element is removed from the DOM & `activeElement` is set to `body`
- This could in theory be fixed by firing `.blur()` on the `document.activeElement` _before_ it's removed, if we can figure out any way to do so

Here's a reduced demo of the basic issue in Safari & Firefox: https://jsfiddle.net/5pcf9L64/

### CODE REVIEW

File: src/Restorer.ts [hunk 1]
```diff
@@ -20,15 +20,28 @@ const EVENT_NAME = "restorer:restorefocus";
 const HISOTRY_DEPTH = 10;
 
 class Restorer extends TabsterPart<RestorerProps> implements RestorerInterface {
+    private _observer: MutationObserver | undefined;
```
Comment (ling1726) [inline src/Restorer.ts:23]: This would start a mutation observer per instance of Restorer - this seems kind of scary performance wise.

We could only have one mutation observer instance on RestorerAPI, to share one mutation observer instance among all Restorer instances

File: src/Restorer.ts [hunk 2]
```diff
@@ -20,15 +20,28 @@ const EVENT_NAME = "restorer:restorefocus";
...
             const element = this._element?.get();
             element?.addEventListener("focusout", this._onFocusOut);
+
+            // Need to also listen to node removals, which do not trigger focus events in non-Chromium browsers
+            const parent = element?.parentElement;
+            if (parent) {
+                this._observer = new MutationObserver(this._onNodeRemoved);
+                this._observer.observe(parent, {
+                    childList: true,
+                    subtree: false,
```
Comment (ling1726) [inline src/Restorer.ts:42]: why is subtree false? a focusable node removal could happen anywhere in the tree

Comment (ling1726) [reply src/Restorer.ts:42]: In this case, there is no need to have a mutation observer per Restorer instance. Tabster already has a mutation observer that will call `dispose` elements with tabster on them. You just need to update the `dispose` function like so 

```ts
dispose(): void {
        if (this._props.type === RestorerTypes.Source) {
            const doc = this._tabster.getWindow().document;
            const element = this._element?.get();
            element?.removeEventListener("focusout", this._onFocusOut);

            if (element && !doc.body.contains(element)) {
                doc.dispatchEvent(
                    new Event(EVENT_NAME, {
                        bubbles: true,
                    })
                );
            }
        }
    }
```

This should fix the issue for all browsers when the element with Restorer it is removed from DOM.

For elements inside the Restorer - the RestorerAPI could have a mutation observer all the Restorer instances (this should probably be opt-in for Restorer through configuration).

File: src/Restorer.ts [hunk 3]
```diff
@@ -49,6 +62,26 @@ class Restorer extends TabsterPart<RestorerProps> implements RestorerInterface {
...
+
+    private _onNodeRemoved = (mutations: MutationRecord[]) => {
+        for (const mutation of mutations) {
+            for (let i = 0; i < mutation.removedNodes.length; i++) {
+                const element = this._element?.get();
+                if (mutation.removedNodes[i] === element) {
+                    const lastFocused =
+                        this._tabster.focusedElement.getFocusedElement();
+                    if (lastFocused && element.contains(lastFocused)) {
+                        document.body?.dispatchEvent(
```
[the remark this answers is not in the document]
Comment (smhigley) [reply src/Restorer.ts:74]: good catch, forgot to update that 😅
